_target_: lightning.Trainer
default_root_dir: paths.output_dir

min_epochs: 1
max_epochs: 5

accelerator: "cpu"
devices: 1

enable_checkpointing: false
fast_dev_run: false

strategy: "auto"
deterministic: false