defaults: 
  - override hydra_logging: colorlog
  - override job_logging: colorlog 

job:
  chdir: True
run:
  dir: ./output/${datamodule.dataset.dataset_name}/${module.model_name}/${now:%Y-%m-%d_%H%M%S}