wandb:
  _target_: pytorch_lightning.loggers.WandbLogger
  _partial_: true
  name: ${model.model_name}_${dataset}_#${seed}
  save_dir: "${paths.log_dir}"
  mode: offline
  id: null # pass correct id to resume experiment!
  project: "gadme"
  log_model: False # upload lightning ckpts
  entity: "deepbirddetect" 
  tags: []
  job_type: ""



