_target_: src.modules.base_module.BaseModule

model:
  _target_: src.modules.models.w2v2.Wav2vec2SequenceClassifier
  checkpoint: facebook/wav2vec2-base-960h
  num_classes: ${datamodule.dataset.n_classes}

loss:
  _target_: torch.nn.CrossEntropyLoss

optimizer:
  _target_: torch.optim.AdamW
  lr: 1e-5
  weight_decay: 0.01

lr_scheduler:
  scheduler:
    _target_: transformers.get_linear_schedule_with_warmup
  extras:
    interval: step
    warmup_ratio: 0.05

metrics: 
  main: 
    _target_: "torchmetrics.classification.Accuracy"
    task: "multiclass"
    num_classes: ${datamodule.dataset.n_classes}
    top_k: 1
  val_best: 
    _target_: "torchmetrics.MaxMetric"

output_activation: 
  _target_: "torch.softmax"
  dim: 1

logging_params:
  on_step: True
  on_epoch: True
  sync_dist: False
  prog_bar: True

model_name: wav2vec2
torch_compile: false

















