_target_: src.dataset.esc50_datamodule.ESC50
data_dir: ${paths.dataset_path}
dataset_name: esc50
feature_extractor_name: ${model.model.checkpoint}
hf_path: ashraq/esc50
hf_name: None
seed: ${seed}
train_batch_size: ${train_batch_size}
eval_batch_size: ${eval_batch_size}
val_split: ${val_split}
column_list: ["input_values", "target"]
n_classes: 50
num_workers: 1
