_target_: src.dataset.highsierra_datamodule.HighSierra
data_dir: ${paths.dataset_path}
dataset_name: high_sierra
feature_extractor_name: ${model.model.checkpoint}
hf_path: DBD-research-group/gadme_v1
hf_name: HSN
seed: ${seed}
train_batch_size: ${train_batch_size}
eval_batch_size: ${eval_batch_size}
val_split: ${val_split}
column_list: ["input_values", "ebird_codes"]
n_classes: 22
num_workers: 10



