model:
  _target_: src.modules.models.wav2vec2.Wav2vec2SequenceClassifier
  checkpoint: facebook/wav2vec2-base-960h
  num_classes: ${datamodule.dataset.n_classes}

model_name: wav2vec2
model_type: raw
torch_compile: false

















