defaults:
  - _self_
  - dataset: sapsucker
  - model: ast
  - callbacks: default
  - paths: default
  - transformations: none

wandb:
  project: birds
  entity: dal-nlp
  group: default
  mode: offline

device: cuda
val_split: .2
random_seed: 1 
train_batch_size: 5
eval_batch_size: 16
print_freq_eval: 25
print_freq_train: 25
check_freq_model: 15

hydra:
  job:
    chdir: True
  run:
    dir: ./output/${dataset.name}/${model.name}/${now:%Y-%m-%d_%H%M%S}