# @package _global_
defaults:
  - _self_
  - datamodule: esc50
  - module: wav2vec2
  - callbacks: default
  - paths: default
  - trainer: single_gpu
  - logger: wandb
  - hydra: default
  - extras: default

  - experiment: null
  - hparams_search: null
  - debug: null

task_name: "train"
ckpt_path: null
seed: 1
