# @package _global_
defaults:
  - _self_
  - datamodule: sapsucker
  - module: wav2vec2
  - callbacks: default
  - paths: default
  - trainer: single_gpu
  - logger: wandb
  - hydra: default
  - experiment: null

#device: cuda
val_split: .2
seed: 1 
train_batch_size: 5
eval_batch_size: 16
print_freq_eval: 25
print_freq_train: 25
check_freq_model: 15

# hydra:
#   job:
#     chdir: True
#   run:
#     dir: ./output/${datamodule.dataset.dataset_name}/${module.model_name}/${now:%Y-%m-%d_%H%M%S}