#NES
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

defaults:
  - _self_
  - transforms: bird_default.yaml
  - extractors: default_aug.yaml
  - loaders: default.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: columbia_costs_rica
  hf_path: DBD-research-group/gadme_v1
  hf_name: columbia_costs_rica
  seed: ${seed}
  feature_extractor:
    _target_: transformers.AutoFeatureExtractor.from_pretrained
    pretrained_model_name_or_path: ${module.network.model.checkpoint}
  n_classes: 90
  n_workers: 3
  column_list: ["input_values", "ebird_code", "ebird_code_multiclass"]
  val_split: 0.2




