_target_: src.datamodule.esc50_datamodule.ESC50

defaults:
  - _self_
  - transforms: esc_default.yaml
  - extractors: default_aug.yaml
  - loaders: default.yaml
  - mapper: null

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: esc50
  hf_path: ashraq/esc50
  hf_name: None
  seed: ${seed}
  # feature_extractor:
  #   _target_: src.utils.extraction.DefaultFeatureExtractor
  #   n_classes: 50
  #   n_workers: 1
  #   column_list: ["input_values", "target"]
  #   sampling_rate: 32_000
  #   return_tensor: 'pt'
  n_classes: 50
  n_workers: 1
  column_list: ["input_values", "target"]
  val_split: 0.2
  task: ${module.task}
  subset: null
  sampling_rate: ${module.network.sampling_rate}