_target_: src.datamodule.esc50_datamodule.ESC50

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: esc50
  hf_path: ashraq/esc50
  hf_name: None
  seed: ${seed}
  feature_extractor: 
    _target_: transformers.AutoFeatureExtractor.from_pretrained
    pretrained_model_name_or_path: ${module.model.checkpoint}
  n_classes: 50
  n_workers: 1
  column_list: ["input_values", "target"]
  val_split: 0.2

loaders:
  train:
    batch_size: 1
    shuffle: True
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  valid:
    batch_size: 1
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  test:
    batch_size: 1
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False

transforms:
  normalize: False
  use_spectrogram: False
  n_fft: null
  hop_length: null
  n_mels: null
  db_scale: null
  waveform_augmentations:
    colored_noise:
      prob: 0.5
      min_snr_in_db: 3.0
      max_snr_in_db: 30.0
      min_f_decay: -2.0
      max_f_decay: 2.0
    #background_noise:
    #    background_paths: "/mnt/home/rheinrich/deep_bird_detect/datapipeline/speech_command_dataset"
    #    prob: 0.5
    #    min_snr_in_db: 3.0
    #    max_snr_in_db: 30.0

  spectrogram_augmentations:
    null

