_target_: src.datamodule.esc50_datamodule.ESC50

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: esc50
  hf_path: ashraq/esc50
  hf_name: None
  seed: ${seed}
  feature_extractor: 
    _target_: transformers.AutoFeatureExtractor.from_pretrained
    pretrained_model_name_or_path: ${module.model.checkpoint}
  n_classes: 50
  n_workers: 1
  column_list: ["input_values", "target"]
  val_split: 0.2

loaders:
  train:
    batch_size: 2
    shuffle: True
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  valid:
    batch_size: 2
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  test:
    batch_size: 2
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False

transforms:
  null
