_target_: src.datamodule.highsierra_datamodule.HighSierra

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: high_sierra
  hf_path: DBD-research-group/gadme_v1
  hf_name: HSN
  seed: ${seed}
  feature_exractor:
    _target_: transformers.AutoFeatureExtractor.from_pretrained
    pretrained_model_name_or_path: ${module.model.checkpoint}
  n_classes: 22
  n_workers: 1
  column_list: ["input_values", "ebird_code"]
  val_split: 0.2

loaders:
  train:
    batch_size: 2
    shuffle: True
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  valid:
    batch_size: 2
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  test:
    batch_size: 2
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False

transforms:
  null





