#HSN high_sierras
_target_: birdset.datamodule.birdset_datamodule.BirdSetDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: HSN
  hf_path: DBD-research-group/BirdSet
  hf_name: HSN
  seed: ${seed}
  # feature_extractor:
  #   _target_: transformers.AutoFeatureExtractor.from_pretrained
  #   pretrained_model_name_or_path: ${module.network.model.checkpoint}
  subset: null
  class_weights_loss: null
  class_weights_sampler: null