#HSN high_sierras
_target_: src.datamodule.subset_datamodules.HSNDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  seed: ${seed}
  # feature_extractor:
  #   _target_: transformers.AutoFeatureExtractor.from_pretrained
  #   pretrained_model_name_or_path: ${module.network.model.checkpoint}
  subset: null
  class_weights_loss: null
  class_weights_sampler: null