#PER amazon basin
_target_: birdset.datamodule.birdset_datamodule.BirdSetDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: PER
  hf_path: DBD-research-group/BirdSet
  hf_name: PER
  seed: ${seed}
  subset: null
  class_weights_loss: null
  class_weights_sampler: null