#SSW
_target_: src.datamodule.gadme_datamodule.GADMEDataModule

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: sapsucker_woods
  hf_path: DBD-research-group/gadme_v1_1
  hf_name: sapsucker_woods
  seed: ${seed}
  feature_extractor: 
    _target_: transformers.AutoFeatureExtractor.from_pretrained
    pretrained_model_name_or_path: ${module.network.model.checkpoint}
  n_classes: 81
  n_workers: 3
  column_list: ["input_values", "ebird_code"]
  val_split: 0.2

loaders:
  train:
    batch_size: 6
    shuffle: True
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  valid:
    batch_size: 6
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False
  
  test:
    batch_size: 6
    shuffle: False
    num_workers: 4
    drop_last: False
    pin_memory: False

transforms:
  use_spectrogram: False
  n_fft: null
  hop_length: null
  n_mels: null
  db_scale: null
  normalize: False
  waveform_augmentations:
    colored_noise:
      prob: 0.5
      min_snr_in_db: 3.0
      max_snr_in_db: 30.0
      min_f_decay: -2.0
      max_f_decay: 2.0
    #background_noise:
    #    background_paths: "/mnt/home/rheinrich/deep_bird_detect/datapipeline/speech_command_dataset"
    #    prob: 0.5
    #    min_snr_in_db: 3.0
    #    max_snr_in_db: 30.0

  spectrogram_augmentations:
    null



