#xcm
_target_: src.datamodule.subset_datamodules.XCLDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  seed: ${seed}
  subset: null
  class_weights_loss: null
  class_weights_sampler: null