#xcm
_target_: birdset.datamodule.pretrain_datamodule.PretrainDataModule

defaults: 
  - _self_
  - transforms: bird_default.yaml
  - loaders: default.yaml
  - mapper: xc_bambird_mapper.yaml

dataset:
  data_dir: ${paths.dataset_path}
  dataset_name: XCM
  hf_path: DBD-research-group/BirdSet
  hf_name: XCM
  seed: ${seed}
  subset: null
  class_weights_loss: null
  class_weights_sampler: null