# @package _global_

task_name: "debug"
train: True
# callbacks: null
#logger: null
module:
  model:
    problem_type: "multi-label-classification"
    
extras: 
  ignore_warnings: False

hydra: 
  job_logging: 
    root:
      level: DEBUG

trainer: 
  max_epochs: 1
  accelerator: cpu
  devices: 1
  detect_anomaly: True
  fast_dev_run: False

datamodule: 
  loaders:
    train: 
      num_workers: 0
      pin_memory: False
    valid: 
      num_workers: 0 
      pin_memory: False
    test:
      num_workers: 0 
      pin_memory: False