_target_: src.datamodule.components.transforms.TransformsWrapper
sampling_rate: ${datamodule.extractors.sampling_rate}
model_type: ${module.network.model_type}

defaults:
  - _self_
  - preprocessing: default.yaml 
  - waveform_augmentations: default.yaml
  - spectrogram_augmentations: default.yaml
  - decoding: bird_event_decoder.yaml
  



